<CategoryRow>:
    orientation: 'horizontal'
    spacing: 10
    size_hint_y: None
    height: 40

    Label:
        text: root.text
        size_hint_x: 0.8

    Button:
        text: "Supprimer"
        size_hint_x: 0.2
        on_release: root.delete_item()

<CategoryRecycleView>:
    viewclass: 'CategoryRow'
    RecycleBoxLayout:
        default_size: None, 40
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'

BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    Button:
        text: "Ajouter une catégorie"
        size_hint_y: None
        height: 50
        on_release: app.root.update_categories()

    CategoryRecycleView:
        id: category_list
